#!/bin/sh -ex
for bundle in classic iota mics slcs; do
  igtf_name=igtf-preinstalled-bundle-${bundle}
  rm -rf "${igtf_name}"
  mkdir -p "${igtf_name}"
  curl -fSs "https://dist.eugridpma.info/distribution/igtf/current/accredited/${igtf_name}.tar.gz" |
    tar -zxC "${igtf_name}"
  openssl rehash -compat "${igtf_name}"
done
