#!/usr/bin/env bash

IGTF="http://dist.eugridpma.info/distribution/igtf/current/accredited"
curl -k \
-O ${IGTF}/igtf-preinstalled-bundle-classic.tar.gz \
-O ${IGTF}/igtf-preinstalled-bundle-iota.tar.gz \
-O ${IGTF}/igtf-preinstalled-bundle-mics.tar.gz \
-O ${IGTF}/igtf-preinstalled-bundle-slcs.tar.gz

for igtf_dist in *.tar.gz; do
    igtf_name="$(basename ${igtf_dist} .tar.gz)"
    rm -rf "${igtf_name}"
    mkdir -p "${igtf_name}"
    tar -x -C "${igtf_name}" -f "${igtf_dist}"
    rm -rf "${igtf_dist}"
done

for d in $(find $(pwd -P) -mindepth 1 -maxdepth 1 -type d | grep -v '.git'); do
    pushd ${d} &> /dev/null;
    pwd
    openssl rehash -compat .;
    popd &> /dev/null;
done

echo '"openssl rehash -compat ." was done on each directory'

